### ISSUE TITLE
Retornar mensagem de erro ao tentar cadastrar matricula já existente

### ISSUE THREAD

**Issue by ithaloazevedo** [fga-eps-mds/2019.2-Amika-Frontend#110]
**Descrição do bug**  
Quando faço o cadastro de uma matricula já cadastrada **NA MESMA TURMA** a aplicação não retorna um erro para o usuário. 

**Comportamento esperado**  
Caso a matricula já esteja cadastrada naquela turma o sistema deve retornar uma mensagem ao usuário.

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessário.
- [x] A issue possui labels.

**Comment by Matheus456** [comment]
Issue duplicada, este problema já havia sido mencionado na issue https://github.com/fga-eps-mds/2019.2-Amika-Frontend/issues/82, de forma geral.
