### ISSUE TITLE
Alterar componentes da sidebar/bottombar do administrador

### ISSUE THREAD

**Issue by Matheus456** [fga-eps-mds/2019.2-Amika-Frontend#123]
**Qual o estado atual, antes do refatoramento? Descreva, por favor.**
Atualmente temos as funcionalidades enviar notificações e disciplina na side/bottom bar.
  
**Descreva qual a necessidade do refatoramento**
Como não iremos ter a funcionalidade de enviar notificações e ainda não temos uma página de disciplina para o administrador escolher entre agenda e materiais, podemos colocar essas duas funcionalidades como tópicos separados da side/bottom bar.
 
**Descreva o resultado esperado apos o refatoramento**

**Informações adicionais**

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

## Critérios de aceitação

- [ ] Os commits seguem a [política de commits do repositório](https://fga-eps-mds.github.io/2019.2-Amika-Wiki/#/docs/projeto/planogerencia).
- [ ] As branches seguem a [política de branches do repositório](https://fga-eps-mds.github.io/2019.2-Amika-Wiki/#/docs/projeto/planogerencia).
- [ ] Não há erros de linter.
- [ ] A build está passando (travis, code climate).
- [ ] As telas seguem a identidade visual da aplicação.

## Telas criadas

**As telas não necessitam seguir exatamente o protótipo, este está apenas como um suporte para sua construção. Entretanto, 
devem não devem conter links de redirecionamento desnecessários, poluição de informações e difícil compreensão de sua utilização.
Enfim, devem seguir boas práticas de usabilidade do usuário.**

**Comment by thefael** [comment]
Bom dia, manos. Uma dúvida: esses ícones e links devem ser alterados pra ambos admin e usuário ou apenas pro admin?

**Comment by thefael** [comment]
Só admin né
