### ISSUE TITLE
Arrumar altura e largura da página desktop

### ISSUE THREAD

**Issue by MateusO97** [fga-eps-mds/2019.2-Amika-Frontend#128]
**Descrição do bug**  

Atualmente a página na versão desktop em todas as telas aparece um scroll vertical para rolar na página, mesmo em telas que nem possuam conteudo

**Para reproduzir**  
Passos para reproduzir o bug:
1. Vá para 'Qualquer tela'
2. Veja o erro

**Comportamento esperado**  

O scroll de rolagem vertical só deveria aparecer quando haja a necessidade, o tamanho da página não deve exceder para que este seja necessário

**Screenshots**  

![image](https://user-images.githubusercontent.com/27258892/69096552-6e65da00-0a33-11ea-93f5-c3ee928ebe06.png)

**Informações adicionais**  

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [x] A issue possui screenshots quando necessário.
- [x] A issue possui labels.

**Comment by Matheus456** [comment]
Está issue foi resolvida em https://github.com/fga-eps-mds/2019.2-Amika-Frontend/pull/141.
