### ISSUE TITLE
[US12] Realizar Agendas da Felicidade

### ISSUE THREAD

**Issue by MateusO97** [fga-eps-mds/2019.2-Amika-Frontend#40]
**Descreva a solução que você gostaria**

Eu, como usuário, responder minhas agendas da felicidade, para desenvolver minhas atividades com maior facilidade durante o semestre.

**Informações adicionais**

Opção de enviar um texto e algum anexo.

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

## Critérios de aceitação

- [ ] Os commits seguem a [política de commits do repositório](https://fga-eps-mds.github.io/2019.2-Amika-Wiki/#/docs/projeto/planogerencia).
- [ ] As branches seguem a [política de branches do repositório](https://fga-eps-mds.github.io/2019.2-Amika-Wiki/#/docs/projeto/planogerencia).
- [ ] Não há erros de linter.
- [ ] A build está passando (travis, code climate).
- [ ] As telas seguem a identidade visual da aplicação.

## Telas criadas

- [ ] Tela da agenda selecionada
- [ ] Listar todas agendas para aluno 

**As telas não necessitam seguir exatamente o protótipo, este está apenas como um suporte para sua construção, e o grupo tem liberdade para criar outras telas, ou simplificar as informações em uma só, apenas comentem na issue antes**

**Comment by MaiconMares** [comment]
@Mateus097 poderia disponibilizar as imagens do protótipo aqui na issue?

**Comment by MateusO97** [comment]
> @MateusO97 poderia disponibilizar as imagens do protótipo aqui na issue?

Essa tela especifica não tinha nenhuma semelhante no protótipo, mas podem tentar fazer algo assim:
![image](https://user-images.githubusercontent.com/27258892/67254457-7e4dc680-f453-11e9-8a0a-a8fd06a47996.png)

Ou assim:
![image](https://user-images.githubusercontent.com/27258892/67254461-83127a80-f453-11e9-848c-77a90e130043.png)

Precisa só ser agradável para o usuário, seguir um pouco nossa identidade visual, para não ficar aquela coisa estática comum, mas vocês tem liberdade para pensar em algum design como queiram também
