### ISSUE TITLE
Criar Template de Issue para Refatoração do Front end

### ISSUE THREAD

**Issue by MateusO97** [fga-eps-mds/2019.2-Amika-Frontend#45]
**Sua funcionalidade requisitada é relacionada com um problema? Descreva, por favor.**

Eu, como desenvolvedor, gostaria de possuir um template de Issue para abrir issues de refatoração, pois atualmente só existem de Bugs e novas funcionalidades.

**Descreva a solução que você gostaria**

Criar um novo template para issues de refatoração, para que possa ser selecionado ao criar uma nova issue, esse template deve possuir perguntas como:
"Porque se deseja refatorar ?"
"Qual o estado atual ?"
"Qual o estado desejado após a refatoração ?

Assim como outras que se considerem relevante

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

**Comment by thefael** [comment]
Boa tarde, mano. Queria saber uma forma de colocar no documento de refatoração como localizar onde é necessária a refatoração. Seria pelo nome do arquivo (ex.: humor.html; humor.css)?
