### ISSUE TITLE
Refatorar Template de Issue de Requisitar Funcionalidade

### ISSUE THREAD

**Issue by MateusO97** [fga-eps-mds/2019.2-Amika-Frontend#46]
**Descrição do bug**  

Template de Issue para requisitar Funcionalidade não consta os critérios de aceitação, e nem as telas a serem criadas.

**Comportamento esperado**  

Adicionar campo de critérios de aceitação(Veja os comentários da issue para entender uma solução aceitavel), e adicionar campo para descrever as telas a serem criadas.

**Screenshots**  

**Informações adicionais**  

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessário.
- [x] A issue possui labels.

**Comment by MateusO97** [comment]
Modelo de como deve ficar o template após as alterações:


**Sua funcionalidade requisitada é relacionada com um problema? Descreva, por favor.**

 

**Descreva a solução que você gostaria**



**Informações adicionais**



**Checklist**  
- [ ] A issue possui nome significativo.
- [ ] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [ ] A issue possui labels.

## Critérios de aceitação

- [ ] Os commits seguem a [política de commits do repositório](https://fga-eps-mds.github.io/2019.2-Amika-Wiki/#/docs/projeto/planogerencia).
- [ ] As branches seguem a [política de branches do repositório](https://fga-eps-mds.github.io/2019.2-Amika-Wiki/#/docs/projeto/planogerencia).
- [ ] Não há erros de linter.
- [ ] A build está passando (travis, code climate).
- [ ] As telas seguem a identidade visual da aplicação.

## Telas criadas


**As telas não necessitam seguir exatamente o protótipo, este está apenas como um suporte para sua construção**

**Comment by MaiconMares** [comment]
Eu preciso especificar algo sobre como as telas devem ser criadas? E o que mais devo adicionar em critérios de aceitação para requisitar funcionalidades? Em minha mente está parecendo que seguir o seu template será muito copiar e colar.

**Comment by MaiconMares** [comment]
A issue está finalizada!

**Comment by MateusO97** [comment]
> Eu preciso especificar algo sobre como as telas devem ser criadas? E o que mais devo adicionar em critérios de aceitação para requisitar funcionalidades? Em minha mente está parecendo que seguir o seu template será muito copiar e colar.

O complicado de especificar como as telas vão ser criadas no template, é que em cada issue seria diferente, então não faria tanto sentido, já a respeito dos critérios de aceitação e de seguir o template, o modelo foi apenas um exemplo de como pode ser feito, mas você tem liberdade para alterar ou adicionar novos critérios que considere importante

**Comment by MateusO97** [comment]
> A issue está finalizada!

Beleza! Lembre de abrir o Pull Request para que eu revise.
