### ISSUE TITLE
[US19] Manter Materiais

### ISSUE THREAD

**Issue by MateusO97** [fga-eps-mds/2019.2-Amika-Frontend#51]
**Sua funcionalidade requisitada é relacionada com um problema? Descreva, por favor.**

Eu, como administrador, gostaria de enviar, alterar e remover materiais(anexos) para com isto divulgar as aulas e outros materiais utilizados na disciplina.

**Descreva a solução que você gostaria**

Página para administrador adicionar, remover, editar materiais, e estes aparecendo em uma página para os alunos visualizarem/baixarem.

**Informações adicionais**

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

## Critérios de aceitação

- [ ] Os commits seguem a [política de commits do repositório](https://fga-eps-mds.github.io/2019.2-Amika-Wiki/#/docs/projeto/planogerencia).
- [ ] As branches seguem a [política de branches do repositório](https://fga-eps-mds.github.io/2019.2-Amika-Wiki/#/docs/projeto/planogerencia).
- [ ] Não há erros de linter.
- [ ] A build está passando (travis, code climate).
- [ ] As telas seguem a identidade visual da aplicação.

## Telas criadas

**As telas não necessitam seguir exatamente o protótipo, este está apenas como um suporte para sua construção. Entretanto, 
devem não devem conter links de redirecionamento desnecessários, poluição de informações e difícil compreensão de sua utilização.
Enfim, devem seguir boas práticas de usabilidade do usuário.**
- Tela administrador gerenciar materiais
- Tela usuário visualizar/baixar materiais

**Comment by thefael** [comment]
Boa tarde, povo. Fiquei na dúvida se, nessa issue, a gente precisa fazer, além da tela do administrador, fazer a pro usuário baixar os arquivos também.
