### ISSUE TITLE
Refatorar perfil aluno

### ISSUE THREAD

**Issue by MateusO97** [fga-eps-mds/2019.2-Amika-Frontend#64]
**Descrição do bug**  

Na model de perfil o nome dos atributos estão como:
- matricula
- nome
- sobrenome

sendo que estes não existem no backend.
Além disso, no perfil.component.ts não existe o atributo error, sendo que esta sendo utilizado um this.error em baixo.

**Para reproduzir**  

**Comportamento esperado**  

Trocar o nome para:
- matricula -> username
- nome -> first_name
- sobrenome -> last_name

E adicionar um atributo
error:any no component.ts de perfil usuario(em baixo do usuario:PerfilUsuario)

**Screenshots**  

**Informações adicionais**  

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessário.
- [x] A issue possui labels.

**Comment by ithaloazevedo** [comment]
Pronto!
