### ISSUE TITLE
Adicionar ícones com a logo da aplicação

### ISSUE THREAD

**Issue by MateusO97** [fga-eps-mds/2019.2-Amika-Frontend#67]
**Descreva a solução que você gostaria**

- Adicionar Favicon com nossa logo(Favicon é o ícone que aparece no navegador)
- Adicionar nossa logo como ícone do aplicativo(no arquivo manifest.webmanifest todos aqueles ícones devem ser substituídos pela nossa logo).

**Informações adicionais**

Removam os ícones atuais do Angular da pasta assets/icons e adicione nossa logo. Deve-se atentar ao tamanho dos ícones, adicione nossa logo nos tamanhos indicados do arquivo manifest.webmanifest. A nossa logo sem nome pode ser encontrada no seguinte link: [Logo](https://github.com/fga-eps-mds/2019.2-Amika-Wiki/blob/DOC45_documentar_sprints/assets/img/AmikasSemNome.png) 
Caso estejam com dificuldades para redimensionar nos tamanhos necessários, informem aqui na issue que eu disponibilizarei nos tamanhos que precisarem.

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

## Critérios de aceitação

- [ ] Os commits seguem a [política de commits do repositório](https://fga-eps-mds.github.io/2019.2-Amika-Wiki/#/docs/projeto/planogerencia).
- [ ] As branches seguem a [política de branches do repositório](https://fga-eps-mds.github.io/2019.2-Amika-Wiki/#/docs/projeto/planogerencia).
- [ ] Não há erros de linter.
- [ ] A build está passando (travis, code climate).
- [ ] As telas seguem a identidade visual da aplicação.

**Comment by Gabrielle-Ribeiro** [comment]
Esse link para a logo não funciona.

**Comment by Gabrielle-Ribeiro** [comment]
E você poderia me disponibilizar a logo nos tamanhos de 384x384 e 512x512, por favor?

**Comment by MateusO97** [comment]
> E você poderia me disponibilizar a logo nos tamanhos de 384x384 e 512x512, por favor?
Na pasta do Drive, dentro da pasta do PO tem uma pasta chamada Logos, e dentro dessa pasta tem uma com tamanhos personalizados, ai lá dentro vai encontrar esta de 384x384 e a de 512x512. Coloquei lá também os arquivos vetorizados.ai que assim consegue abrir em algum programa de edição caso precise de outros tamanhos
