### ISSUE TITLE
Criar página de rota não encontrada (404)

### ISSUE THREAD

**Issue by Matheus456** [fga-eps-mds/2019.2-Amika-Frontend#68]
**Sua funcionalidade requisitada é relacionada com um problema? Descreva, por favor.**
Atualmente quando o usuário tenta navegar em uma página que não está definida na rota, ele simplesmente vai para uma página branca.
 

**Descreva a solução que você gostaria**
Gostaria que existisse uma página personalizada de não encontrado, que retornasse o estado 404 e a mensagem.

**Informações adicionais**

**Checklist**  
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [ ] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

## Critérios de aceitação

- [ ] Os commits seguem a [política de commits do repositório](https://fga-eps-mds.github.io/2019.2-Amika-Wiki/#/docs/projeto/planogerencia).
- [x] As branches seguem a [política de branches do repositório](https://fga-eps-mds.github.io/2019.2-Amika-Wiki/#/docs/projeto/planogerencia).
- [ ] Não há erros de linter.
- [x] A build está passando (travis, code climate).
- [ ] As telas seguem a identidade visual da aplicação.

## Telas criadas

**As telas não necessitam seguir exatamente o protótipo, este está apenas como um suporte para sua construção. Entretanto, 
devem não devem conter links de redirecionamento desnecessários, poluição de informações e difícil compreensão de sua utilização.
Enfim, devem seguir boas práticas de usabilidade do usuário.**

**Comment by thefael** [comment]
Adicionei uma página pro erro 404. Queria saber se coloco um link pra página inicial nessa página também, qq cê acha?

**Comment by thefael** [comment]
Já está funcionando caso o usuário tente entrar em um link que não existe, por exemplo: "http://localhost:4200/issoNaoExiste" >> esse link redireciona pra página 404.
